### ISSUE TITLE
DIstinguish between Solar absorptance and thermal absorptance (amissivity)

### ISSUE THREAD

**Issue by dccurcija** [ise621/building-envelope-data#184]
To avoid confusion we should just call solar absorptance "Absorptance" and use "Emissivity" for thermal emittance only.

**Comment by christoph-maurer** [comment]
One of the goals for designing the API specification was "The meaning of a valid data set will be unambiguous." If we allow `absorptance` and `emissivity`, some data sets will use the wrong key and then it's not clear which part is wrong.
Another design goal was "Facilitate re-use of the data schemas by keeping them modular." `absorptance` and `emissivity` reduce the reuse and increase the complexity.
Last, the design goal "The API should enable efficient data exchange." can be achieved better without `absorptance` and `emissivity`, because it becomes easier to check that `absorptanceEmittance` + `transmittance` + `reflectance` = 1 .

**Comment by christoph-maurer** [comment]
If you don't agree that this issue was solved, please reopen it!
