### ISSUE TITLE
Add BSDF resources

### ISSUE THREAD

**Issue by christoph-maurer** [ise621/building-envelope-data#249]
I got feedback from software companies that they are interested in using BSDF data from IGSDB.

@StephenCzarnecki How do you estimate the effort to add resources in the LBNL/Klems XML format to the components which have such data? I have created the `dataFormatId` e021cf20-e887-4dce-ad27-35da70cec472 .

**Comment by StephenCzarnecki** [comment]
@christoph-maurer Do you mean to just add a url to download the XML data as another resource in the metadata?  I do not think that will be difficult.  However I would first like to describe the current implementation in the IGSDB so everyone can have the same understanding.

In the current IGSDB implementations (both igsdb.lbl.gov and igsdb-icon.herokuapp.com) if a product has a bsdf xml file it is available under the IGSDB REST api like /api/v1/products/{igsdb_id}/datafile.

For example in igsdb-icon.herokuapp.com the manufacturer Glen Raven has a product named "FF 4603-0000" that is represented by a bsdf.  This has an IGSDB ID of 13321 (and for reference a CGDB ID of 10057).  And it has some information available at https://igsdb-icon.herokuapp.com/api/v1/products/13321.  However the BSDF XML data is available at https://igsdb-icon.herokuapp.com/api/v1/products/13321/datafile

Is the proposal for bsdf products to have a second resource in the metadata with the /datafile url?  So the above product would have two resources, one with `locator` https://igsdb-icon.herokuapp.com/api/v1/products/13321 and a second with `locator` https://igsdb-icon.herokuapp.com/api/v1/products/13321/datafile  `dataFormatId` that corresponds to "LBNL/Klems XML" (e021cf20-e887-4dce-ad27-35da70cec472)

A quick note:  https://igsdb-icon.herokuapp.com/api/v1/products/13321/?json_format=buildingenvelopedata.org throws a 500 error from the server.  This is because the product is not a glazing product.  Only glazing products have been translated to the ICON json format.  So this product is hitting an error somewhere in the process of serializing to the ICON format which should get resolved during work on serializing shading layers.

**Comment by christoph-maurer** [comment]
@StephenCzarnecki Thanks for the note and the explanations!

> Is the proposal for bsdf products to have a second resource in the metadata with the /datafile url? So the above product would have two resources, one with locator https://igsdb-icon.herokuapp.com/api/v1/products/13321 and a second with locator https://igsdb-icon.herokuapp.com/api/v1/products/13321/datafile dataFormatId that corresponds to "LBNL/Klems XML" (e021cf20-e887-4dce-ad27-35da70cec472)

That's exactly what I was hoping for.

**Comment by christoph-maurer** [comment]
@StephenCzarnecki asked:

> @christoph-maurer Can you provide an example of how this example using IGSDB ID 13321 would look like as a `GetHttpsResource`? I still do not think I am completely clear how this structure should work.

**Comment by christoph-maurer** [comment]
@StephenCzarnecki Do you think it is possible to implement the BSDF files and the `dataFormatId` until August 24? @simon-wacker could then implement it into metabase on August 25 before he is out of office for three weeks. The feature would be very helpful in our discussions with software companies about a follow-up project.

**Comment by christoph-maurer** [comment]
Thank you, @StephenCzarnecki ! This is very helpful.
